version: "3.8"
services:
  tsundoku:
    image: tylergibbs2/tsundoku:latest
    container_name: tsundoku
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - <path to data folder>:/app/data
      - <path to downloaded>:/downloaded
      - <path to target location>:/target
    ports:
      - "6439:6439"
    restart: unless-stopped
