// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddNyaaResultData,
  AddNyaaResultErrors,
  AddNyaaResultResponses,
  AddSeenReleasesData,
  AddSeenReleasesErrors,
  AddSeenReleasesResponses,
  ChangePasswordData,
  ChangePasswordErrors,
  ChangePasswordResponses,
  CheckForReleasesData,
  CheckForReleasesResponses,
  CreateLibraryData,
  CreateLibraryErrors,
  CreateLibraryResponses,
  CreateShowData,
  CreateShowEntriesData,
  CreateShowEntriesErrors,
  CreateShowEntriesResponses,
  CreateShowErrors,
  CreateShowResponses,
  CreateWebhookBaseData,
  CreateWebhookBaseErrors,
  CreateWebhookBaseResponses,
  DeleteLibraryData,
  DeleteLibraryErrors,
  DeleteLibraryResponses,
  DeleteShowCacheData,
  DeleteShowCacheErrors,
  DeleteShowCacheResponses,
  DeleteShowData,
  DeleteShowEntryData,
  DeleteShowEntryErrors,
  DeleteShowEntryResponses,
  DeleteShowErrors,
  DeleteShowResponses,
  DeleteWebhookBaseData,
  DeleteWebhookBaseErrors,
  DeleteWebhookBaseResponses,
  DistinctSeenReleasesData,
  DistinctSeenReleasesErrors,
  DistinctSeenReleasesResponses,
  FilterSeenReleasesData,
  FilterSeenReleasesErrors,
  FilterSeenReleasesResponses,
  GetApiTokenData,
  GetApiTokenResponses,
  GetEntryData,
  GetEntryErrors,
  GetEntryResponses,
  GetFeedsConfigData,
  GetFeedsConfigResponses,
  GetGeneralConfigData,
  GetGeneralConfigResponses,
  GetLibrariesData,
  GetLibrariesResponses,
  GetLibraryData,
  GetLibraryErrors,
  GetLibraryResponses,
  GetShowData,
  GetShowEntriesData,
  GetShowEntriesErrors,
  GetShowEntriesResponses,
  GetShowEntryData,
  GetShowEntryErrors,
  GetShowEntryResponses,
  GetShowErrors,
  GetShowResponses,
  GetShowsData,
  GetShowsErrors,
  GetShowsResponses,
  GetShowWebhooksData,
  GetShowWebhooksErrors,
  GetShowWebhooksResponses,
  GetTorrentConfigData,
  GetTorrentConfigResponses,
  GetWebhookBaseData,
  GetWebhookBaseErrors,
  GetWebhookBaseResponses,
  GetWebhookBasesData,
  GetWebhookBasesResponses,
  RegenerateApiTokenData,
  RegenerateApiTokenResponses,
  SearchNyaaData,
  SearchNyaaErrors,
  SearchNyaaResponses,
  TestTorrentClientData,
  TestTorrentClientResponses,
  TreeData,
  TreeErrors,
  TreeResponses,
  UpdateFeedsConfigData,
  UpdateFeedsConfigErrors,
  UpdateFeedsConfigResponses,
  UpdateGeneralConfigData,
  UpdateGeneralConfigErrors,
  UpdateGeneralConfigResponses,
  UpdateLibraryData,
  UpdateLibraryErrors,
  UpdateLibraryResponses,
  UpdateShowData,
  UpdateShowErrors,
  UpdateShowResponses,
  UpdateShowWebhookData,
  UpdateShowWebhookErrors,
  UpdateShowWebhookResponses,
  UpdateTorrentConfigData,
  UpdateTorrentConfigErrors,
  UpdateTorrentConfigResponses,
  UpdateWebhookBaseData,
  UpdateWebhookBaseErrors,
  UpdateWebhookBaseResponses,
  WebhookIsValidData,
  WebhookIsValidErrors,
  WebhookIsValidResponses,
} from "./types.gen";
import {
  zAddNyaaResultBody,
  zAddNyaaResultResponse,
  zAddSeenReleasesBody,
  zAddSeenReleasesResponse,
  zChangePasswordBody,
  zChangePasswordResponse,
  zCheckForReleasesResponse,
  zCreateLibraryBody,
  zCreateLibraryResponse,
  zCreateShowBody,
  zCreateShowEntriesPath,
  zCreateShowEntriesResponse,
  zCreateShowResponse,
  zCreateWebhookBaseBody,
  zCreateWebhookBaseResponse,
  zDeleteLibraryPath,
  zDeleteLibraryResponse,
  zDeleteShowCachePath,
  zDeleteShowCacheResponse,
  zDeleteShowEntryPath,
  zDeleteShowEntryResponse,
  zDeleteShowPath,
  zDeleteShowResponse,
  zDeleteWebhookBasePath,
  zDeleteWebhookBaseResponse,
  zDistinctSeenReleasesQuery,
  zDistinctSeenReleasesResponse,
  zFilterSeenReleasesQuery,
  zFilterSeenReleasesResponse,
  zGetApiTokenResponse,
  zGetEntryPath,
  zGetEntryResponse,
  zGetFeedsConfigResponse,
  zGetGeneralConfigResponse,
  zGetLibrariesResponse,
  zGetLibraryPath,
  zGetLibraryResponse,
  zGetShowEntriesPath,
  zGetShowEntriesResponse,
  zGetShowEntryPath,
  zGetShowEntryResponse,
  zGetShowPath,
  zGetShowResponse,
  zGetShowsQuery,
  zGetShowsResponse,
  zGetShowWebhooksPath,
  zGetShowWebhooksResponse,
  zGetTorrentConfigResponse,
  zGetWebhookBasePath,
  zGetWebhookBaseResponse,
  zGetWebhookBasesResponse,
  zRegenerateApiTokenResponse,
  zSearchNyaaQuery,
  zSearchNyaaResponse,
  zTestTorrentClientResponse,
  zTreeBody,
  zTreeResponse,
  zUpdateFeedsConfigBody,
  zUpdateFeedsConfigResponse,
  zUpdateGeneralConfigBody,
  zUpdateGeneralConfigResponse,
  zUpdateLibraryBody,
  zUpdateLibraryPath,
  zUpdateLibraryResponse,
  zUpdateShowBody,
  zUpdateShowPath,
  zUpdateShowResponse,
  zUpdateShowWebhookBody,
  zUpdateShowWebhookPath,
  zUpdateShowWebhookResponse,
  zUpdateTorrentConfigBody,
  zUpdateTorrentConfigResponse,
  zUpdateWebhookBaseBody,
  zUpdateWebhookBasePath,
  zUpdateWebhookBaseResponse,
  zWebhookIsValidPath,
  zWebhookIsValidResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Tree
 */
export const tree = <ThrowOnError extends boolean = false>(
  options: Options<TreeData, ThrowOnError>
): RequestResult<TreeResponses, TreeErrors, ThrowOnError> =>
  (options.client ?? client).post<TreeResponses, TreeErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zTreeBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zTreeResponse.parseAsync(data),
    url: "/api/v1/tree",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Api Token
 */
export const getApiToken = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiTokenData, ThrowOnError>
): RequestResult<GetApiTokenResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiTokenResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetApiTokenResponse.parseAsync(data),
    url: "/api/v1/config/token",
    ...options,
  });

/**
 * Regenerate Api Token
 */
export const regenerateApiToken = <ThrowOnError extends boolean = false>(
  options?: Options<RegenerateApiTokenData, ThrowOnError>
): RequestResult<RegenerateApiTokenResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    RegenerateApiTokenResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zRegenerateApiTokenResponse.parseAsync(data),
    url: "/api/v1/config/token",
    ...options,
  });

/**
 * Get General Config
 */
export const getGeneralConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeneralConfigData, ThrowOnError>
): RequestResult<GetGeneralConfigResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetGeneralConfigResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetGeneralConfigResponse.parseAsync(data),
    url: "/api/v1/config/general",
    ...options,
  });

/**
 * Update General Config
 */
export const updateGeneralConfig = <ThrowOnError extends boolean = false>(
  options: Options<UpdateGeneralConfigData, ThrowOnError>
): RequestResult<
  UpdateGeneralConfigResponses,
  UpdateGeneralConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateGeneralConfigResponses,
    UpdateGeneralConfigErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateGeneralConfigBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateGeneralConfigResponse.parseAsync(data),
    url: "/api/v1/config/general",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Feeds Config
 */
export const getFeedsConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetFeedsConfigData, ThrowOnError>
): RequestResult<GetFeedsConfigResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetFeedsConfigResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetFeedsConfigResponse.parseAsync(data),
    url: "/api/v1/config/feeds",
    ...options,
  });

/**
 * Update Feeds Config
 */
export const updateFeedsConfig = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFeedsConfigData, ThrowOnError>
): RequestResult<
  UpdateFeedsConfigResponses,
  UpdateFeedsConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateFeedsConfigResponses,
    UpdateFeedsConfigErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateFeedsConfigBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateFeedsConfigResponse.parseAsync(data),
    url: "/api/v1/config/feeds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Torrent Config
 */
export const getTorrentConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetTorrentConfigData, ThrowOnError>
): RequestResult<GetTorrentConfigResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetTorrentConfigResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetTorrentConfigResponse.parseAsync(data),
    url: "/api/v1/config/torrent",
    ...options,
  });

/**
 * Update Torrent Config
 */
export const updateTorrentConfig = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTorrentConfigData, ThrowOnError>
): RequestResult<
  UpdateTorrentConfigResponses,
  UpdateTorrentConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateTorrentConfigResponses,
    UpdateTorrentConfigErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateTorrentConfigBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateTorrentConfigResponse.parseAsync(data),
    url: "/api/v1/config/torrent",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Test Torrent Client
 */
export const testTorrentClient = <ThrowOnError extends boolean = false>(
  options?: Options<TestTorrentClientData, ThrowOnError>
): RequestResult<TestTorrentClientResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    TestTorrentClientResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zTestTorrentClientResponse.parseAsync(data),
    url: "/api/v1/config/torrent/test",
    ...options,
  });

/**
 * Check For Releases
 *
 * Force Tsundoku to check all enabled RSS feeds for new releases.
 */
export const checkForReleases = <ThrowOnError extends boolean = false>(
  options?: Options<CheckForReleasesData, ThrowOnError>
): RequestResult<CheckForReleasesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CheckForReleasesResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCheckForReleasesResponse.parseAsync(data),
    url: "/api/v1/shows/check",
    ...options,
  });

/**
 * Delete Show Cache
 *
 * Force Tsundoku to delete the poster cache for a show.
 */
export const deleteShowCache = <ThrowOnError extends boolean = false>(
  options: Options<DeleteShowCacheData, ThrowOnError>
): RequestResult<
  DeleteShowCacheResponses,
  DeleteShowCacheErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteShowCacheResponses,
    DeleteShowCacheErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteShowCachePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDeleteShowCacheResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/cache",
    ...options,
  });

/**
 * Webhook Is Valid
 *
 * Check if a Webhook is valid with the service it is for.
 */
export const webhookIsValid = <ThrowOnError extends boolean = false>(
  options: Options<WebhookIsValidData, ThrowOnError>
): RequestResult<WebhookIsValidResponses, WebhookIsValidErrors, ThrowOnError> =>
  (options.client ?? client).get<
    WebhookIsValidResponses,
    WebhookIsValidErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zWebhookIsValidPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zWebhookIsValidResponse.parseAsync(data),
    url: "/api/v1/webhooks/{base_id}/valid",
    ...options,
  });

/**
 * Change Password
 */
export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>
): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ChangePasswordResponses,
    ChangePasswordErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zChangePasswordBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zChangePasswordResponse.parseAsync(data),
    url: "/api/v1/account/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Shows
 */
export const getShows = <ThrowOnError extends boolean = false>(
  options?: Options<GetShowsData, ThrowOnError>
): RequestResult<GetShowsResponses, GetShowsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetShowsResponses,
    GetShowsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetShowsQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetShowsResponse.parseAsync(data),
    url: "/api/v1/shows",
    ...options,
  });

/**
 * Create Show
 */
export const createShow = <ThrowOnError extends boolean = false>(
  options: Options<CreateShowData, ThrowOnError>
): RequestResult<CreateShowResponses, CreateShowErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateShowResponses,
    CreateShowErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateShowBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateShowResponse.parseAsync(data),
    url: "/api/v1/shows",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Show
 */
export const deleteShow = <ThrowOnError extends boolean = false>(
  options: Options<DeleteShowData, ThrowOnError>
): RequestResult<DeleteShowResponses, DeleteShowErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteShowResponses,
    DeleteShowErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteShowPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDeleteShowResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}",
    ...options,
  });

/**
 * Get Show
 */
export const getShow = <ThrowOnError extends boolean = false>(
  options: Options<GetShowData, ThrowOnError>
): RequestResult<GetShowResponses, GetShowErrors, ThrowOnError> =>
  (options.client ?? client).get<GetShowResponses, GetShowErrors, ThrowOnError>(
    {
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: zGetShowPath,
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseValidator: async (data) =>
        await zGetShowResponse.parseAsync(data),
      url: "/api/v1/shows/{show_id}",
      ...options,
    }
  );

/**
 * Update Show
 */
export const updateShow = <ThrowOnError extends boolean = false>(
  options: Options<UpdateShowData, ThrowOnError>
): RequestResult<UpdateShowResponses, UpdateShowErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateShowResponses,
    UpdateShowErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateShowBody,
          path: zUpdateShowPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateShowResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Show Entries
 */
export const getShowEntries = <ThrowOnError extends boolean = false>(
  options: Options<GetShowEntriesData, ThrowOnError>
): RequestResult<GetShowEntriesResponses, GetShowEntriesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetShowEntriesResponses,
    GetShowEntriesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetShowEntriesPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetShowEntriesResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/entries",
    ...options,
  });

/**
 * Create Show Entries
 */
export const createShowEntries = <ThrowOnError extends boolean = false>(
  options: Options<CreateShowEntriesData, ThrowOnError>
): RequestResult<
  CreateShowEntriesResponses,
  CreateShowEntriesErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateShowEntriesResponses,
    CreateShowEntriesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zCreateShowEntriesPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateShowEntriesResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/entries",
    ...options,
  });

/**
 * Delete Show Entry
 */
export const deleteShowEntry = <ThrowOnError extends boolean = false>(
  options: Options<DeleteShowEntryData, ThrowOnError>
): RequestResult<
  DeleteShowEntryResponses,
  DeleteShowEntryErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteShowEntryResponses,
    DeleteShowEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteShowEntryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDeleteShowEntryResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/entries/{entry_id}",
    ...options,
  });

/**
 * Get Show Entry
 */
export const getShowEntry = <ThrowOnError extends boolean = false>(
  options: Options<GetShowEntryData, ThrowOnError>
): RequestResult<GetShowEntryResponses, GetShowEntryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetShowEntryResponses,
    GetShowEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetShowEntryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetShowEntryResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/entries/{entry_id}",
    ...options,
  });

/**
 * Get Entry
 */
export const getEntry = <ThrowOnError extends boolean = false>(
  options: Options<GetEntryData, ThrowOnError>
): RequestResult<GetEntryResponses, GetEntryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetEntryResponses,
    GetEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetEntryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetEntryResponse.parseAsync(data),
    url: "/api/v1/entries/{entry_id}",
    ...options,
  });

/**
 * Get Show Webhooks
 */
export const getShowWebhooks = <ThrowOnError extends boolean = false>(
  options: Options<GetShowWebhooksData, ThrowOnError>
): RequestResult<
  GetShowWebhooksResponses,
  GetShowWebhooksErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetShowWebhooksResponses,
    GetShowWebhooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetShowWebhooksPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetShowWebhooksResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/webhooks",
    ...options,
  });

/**
 * Update Show Webhook
 */
export const updateShowWebhook = <ThrowOnError extends boolean = false>(
  options: Options<UpdateShowWebhookData, ThrowOnError>
): RequestResult<
  UpdateShowWebhookResponses,
  UpdateShowWebhookErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateShowWebhookResponses,
    UpdateShowWebhookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateShowWebhookBody,
          path: zUpdateShowWebhookPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateShowWebhookResponse.parseAsync(data),
    url: "/api/v1/shows/{show_id}/webhooks/{base_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Webhook Bases
 */
export const getWebhookBases = <ThrowOnError extends boolean = false>(
  options?: Options<GetWebhookBasesData, ThrowOnError>
): RequestResult<GetWebhookBasesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWebhookBasesResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetWebhookBasesResponse.parseAsync(data),
    url: "/api/v1/webhooks",
    ...options,
  });

/**
 * Create Webhook Base
 */
export const createWebhookBase = <ThrowOnError extends boolean = false>(
  options: Options<CreateWebhookBaseData, ThrowOnError>
): RequestResult<
  CreateWebhookBaseResponses,
  CreateWebhookBaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateWebhookBaseResponses,
    CreateWebhookBaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateWebhookBaseBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateWebhookBaseResponse.parseAsync(data),
    url: "/api/v1/webhooks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Webhook Base
 */
export const deleteWebhookBase = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWebhookBaseData, ThrowOnError>
): RequestResult<
  DeleteWebhookBaseResponses,
  DeleteWebhookBaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteWebhookBaseResponses,
    DeleteWebhookBaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteWebhookBasePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDeleteWebhookBaseResponse.parseAsync(data),
    url: "/api/v1/webhooks/{base_id}",
    ...options,
  });

/**
 * Get Webhook Base
 */
export const getWebhookBase = <ThrowOnError extends boolean = false>(
  options: Options<GetWebhookBaseData, ThrowOnError>
): RequestResult<GetWebhookBaseResponses, GetWebhookBaseErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetWebhookBaseResponses,
    GetWebhookBaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetWebhookBasePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetWebhookBaseResponse.parseAsync(data),
    url: "/api/v1/webhooks/{base_id}",
    ...options,
  });

/**
 * Update Webhook Base
 */
export const updateWebhookBase = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWebhookBaseData, ThrowOnError>
): RequestResult<
  UpdateWebhookBaseResponses,
  UpdateWebhookBaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateWebhookBaseResponses,
    UpdateWebhookBaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateWebhookBaseBody,
          path: zUpdateWebhookBasePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateWebhookBaseResponse.parseAsync(data),
    url: "/api/v1/webhooks/{base_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Filter Seen Releases
 */
export const filterSeenReleases = <ThrowOnError extends boolean = false>(
  options?: Options<FilterSeenReleasesData, ThrowOnError>
): RequestResult<
  FilterSeenReleasesResponses,
  FilterSeenReleasesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    FilterSeenReleasesResponses,
    FilterSeenReleasesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zFilterSeenReleasesQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zFilterSeenReleasesResponse.parseAsync(data),
    url: "/api/v1/seen_releases/filter",
    ...options,
  });

/**
 * Distinct Seen Releases
 */
export const distinctSeenReleases = <ThrowOnError extends boolean = false>(
  options: Options<DistinctSeenReleasesData, ThrowOnError>
): RequestResult<
  DistinctSeenReleasesResponses,
  DistinctSeenReleasesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    DistinctSeenReleasesResponses,
    DistinctSeenReleasesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zDistinctSeenReleasesQuery,
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDistinctSeenReleasesResponse.parseAsync(data),
    url: "/api/v1/seen_releases/distinct",
    ...options,
  });

/**
 * Add Seen Releases
 *
 * Searches Nyaa for a title/release group and persists any results as
 * seen releases, keyed to the caller's chosen title/group so that adding
 * the show later pulls them in. Returns how many *additional* releases now
 * match the (title, release group, resolution) criteria and the resulting
 * episode list.
 */
export const addSeenReleases = <ThrowOnError extends boolean = false>(
  options: Options<AddSeenReleasesData, ThrowOnError>
): RequestResult<
  AddSeenReleasesResponses,
  AddSeenReleasesErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddSeenReleasesResponses,
    AddSeenReleasesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zAddSeenReleasesBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zAddSeenReleasesResponse.parseAsync(data),
    url: "/api/v1/seen_releases/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Nyaa
 */
export const searchNyaa = <ThrowOnError extends boolean = false>(
  options?: Options<SearchNyaaData, ThrowOnError>
): RequestResult<SearchNyaaResponses, SearchNyaaErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    SearchNyaaResponses,
    SearchNyaaErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zSearchNyaaQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zSearchNyaaResponse.parseAsync(data),
    url: "/api/v1/nyaa",
    ...options,
  });

/**
 * Add Nyaa Result
 */
export const addNyaaResult = <ThrowOnError extends boolean = false>(
  options: Options<AddNyaaResultData, ThrowOnError>
): RequestResult<AddNyaaResultResponses, AddNyaaResultErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AddNyaaResultResponses,
    AddNyaaResultErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zAddNyaaResultBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zAddNyaaResultResponse.parseAsync(data),
    url: "/api/v1/nyaa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Libraries
 */
export const getLibraries = <ThrowOnError extends boolean = false>(
  options?: Options<GetLibrariesData, ThrowOnError>
): RequestResult<GetLibrariesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetLibrariesResponses, unknown, ThrowOnError>(
    {
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseValidator: async (data) =>
        await zGetLibrariesResponse.parseAsync(data),
      url: "/api/v1/libraries",
      ...options,
    }
  );

/**
 * Create Library
 */
export const createLibrary = <ThrowOnError extends boolean = false>(
  options: Options<CreateLibraryData, ThrowOnError>
): RequestResult<CreateLibraryResponses, CreateLibraryErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateLibraryResponses,
    CreateLibraryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateLibraryBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateLibraryResponse.parseAsync(data),
    url: "/api/v1/libraries",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Library
 */
export const deleteLibrary = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLibraryData, ThrowOnError>
): RequestResult<DeleteLibraryResponses, DeleteLibraryErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteLibraryResponses,
    DeleteLibraryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteLibraryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zDeleteLibraryResponse.parseAsync(data),
    url: "/api/v1/libraries/{library_id}",
    ...options,
  });

/**
 * Get Library
 */
export const getLibrary = <ThrowOnError extends boolean = false>(
  options: Options<GetLibraryData, ThrowOnError>
): RequestResult<GetLibraryResponses, GetLibraryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetLibraryResponses,
    GetLibraryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetLibraryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetLibraryResponse.parseAsync(data),
    url: "/api/v1/libraries/{library_id}",
    ...options,
  });

/**
 * Update Library
 */
export const updateLibrary = <ThrowOnError extends boolean = false>(
  options: Options<UpdateLibraryData, ThrowOnError>
): RequestResult<UpdateLibraryResponses, UpdateLibraryErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateLibraryResponses,
    UpdateLibraryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateLibraryBody,
          path: zUpdateLibraryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zUpdateLibraryResponse.parseAsync(data),
    url: "/api/v1/libraries/{library_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
