// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
};

/**
 * DirectoryTree
 */
export type DirectoryTree = {
  /**
   * Root Is Writable
   */
  root_is_writable: boolean;
  /**
   * Can Go Back
   */
  can_go_back: boolean;
  /**
   * Current Path
   */
  current_path: string;
  /**
   * Children
   */
  children: Array<string>;
};

/**
 * Entry
 */
export type Entry = {
  /**
   * Id
   */
  id: number;
  /**
   * Show Id
   */
  show_id: number;
  /**
   * Episode
   */
  episode: number;
  /**
   * Version
   */
  version: string;
  state: EntryState;
  /**
   * Torrent Hash
   */
  torrent_hash: string;
  /**
   * Created Manually
   */
  created_manually: boolean;
  /**
   * Last Update
   */
  last_update: string;
  /**
   * File Path
   */
  file_path?: string;
};

/**
 * EntryState
 *
 * Represents the state of an Entry.
 *
 * Matches exactly with the Postgres enum.
 */
export type EntryState =
  | "downloading"
  | "downloaded"
  | "renamed"
  | "moved"
  | "completed"
  | "failed";

/**
 * FeedsConfigResponse
 */
export type FeedsConfigResponse = {
  /**
   * Polling Interval
   */
  polling_interval: number;
  /**
   * Complete Check Interval
   */
  complete_check_interval: number;
  /**
   * Fuzzy Cutoff
   */
  fuzzy_cutoff: number;
  /**
   * Seed Ratio Limit
   */
  seed_ratio_limit: number;
};

/**
 * FeedsConfigUpdate
 */
export type FeedsConfigUpdate = {
  /**
   * Polling Interval
   */
  polling_interval?: number | null;
  /**
   * Complete Check Interval
   */
  complete_check_interval?: number | null;
  /**
   * Fuzzy Cutoff
   */
  fuzzy_cutoff?: number | null;
  /**
   * Seed Ratio Limit
   */
  seed_ratio_limit?: number | null;
};

export type FoundEntry = [number, number];

/**
 * GeneralConfigResponse
 */
export type GeneralConfigResponse = {
  /**
   * Host
   */
  host: string;
  /**
   * Port
   */
  port: number;
  /**
   * Update Do Check
   */
  update_do_check: boolean;
  /**
   * Locale
   */
  locale: string;
  /**
   * Log Level
   */
  log_level: string;
  /**
   * Default Desired Format
   */
  default_desired_format: string;
  /**
   * Unwatch When Finished
   */
  unwatch_when_finished: boolean;
  /**
   * Use Season Folder
   */
  use_season_folder: boolean;
};

/**
 * GeneralConfigUpdate
 */
export type GeneralConfigUpdate = {
  /**
   * Host
   */
  host?: string | null;
  /**
   * Port
   */
  port?: number | null;
  /**
   * Update Do Check
   */
  update_do_check?: boolean | null;
  /**
   * Locale
   */
  locale?: string | null;
  /**
   * Log Level
   */
  log_level?: string | null;
  /**
   * Default Desired Format
   */
  default_desired_format?: string | null;
  /**
   * Unwatch When Finished
   */
  unwatch_when_finished?: boolean | null;
  /**
   * Use Season Folder
   */
  use_season_folder?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * KitsuManager
 */
export type KitsuManager = {
  /**
   * Show Id
   */
  show_id: number;
  /**
   * Kitsu Id
   */
  kitsu_id?: number | null;
  /**
   * Slug
   */
  slug?: string | null;
  /**
   * Status
   */
  status?: string | null;
  /**
   * Poster
   */
  poster?: string | null;
  /**
   * Link
   *
   * The show's page on Kitsu, derived from its Kitsu ID.
   */
  readonly link: string | null;
  /**
   * Html Status
   *
   * A localized, styled HTML span describing the show's status.
   */
  readonly html_status: string | null;
};

/**
 * Library
 */
export type Library = {
  /**
   * Id
   */
  id_: number;
  /**
   * Folder
   */
  folder: string;
  /**
   * Is Default
   */
  is_default: boolean;
};

/**
 * LibraryCreate
 */
export type LibraryCreate = {
  /**
   * Folder
   */
  folder: string;
};

/**
 * LibraryUpdate
 */
export type LibraryUpdate = {
  /**
   * Folder
   */
  folder: string;
  /**
   * Is Default
   */
  is_default?: boolean;
};

/**
 * NyaaResult
 */
export type NyaaResult = {
  /**
   * Show Id
   */
  show_id: number | null;
  /**
   * Title
   */
  title: string;
  /**
   * Published
   */
  published: string;
  /**
   * Torrent Link
   */
  torrent_link: string;
  /**
   * Post Link
   */
  post_link: string;
  /**
   * Size
   */
  size: string;
  /**
   * Seeders
   */
  seeders: number;
  /**
   * Leechers
   */
  leechers: number;
};

/**
 * NyaaShowRequest
 */
export type NyaaShowRequest = {
  /**
   * Show Id
   */
  show_id: number;
  /**
   * Torrent Link
   */
  torrent_link: string;
  /**
   * Overwrite
   */
  overwrite?: boolean;
};

/**
 * Pagination
 */
export type Pagination = {
  /**
   * Page
   */
  page: number;
  /**
   * Limit
   */
  limit: number;
  /**
   * Total
   */
  total: number;
  /**
   * Pages
   */
  pages: number;
};

/**
 * SeenRelease
 */
export type SeenRelease = {
  /**
   * Title
   */
  title: string;
  /**
   * Release Group
   */
  release_group: string;
  /**
   * Episode
   */
  episode: number;
  /**
   * Resolution
   */
  resolution: string;
  /**
   * Version
   */
  version: string;
  /**
   * Torrent Destination
   */
  torrent_destination: string;
  /**
   * Seen At
   */
  seen_at: string;
};

/**
 * SeenReleaseAddRequest
 */
export type SeenReleaseAddRequest = {
  /**
   * Title
   */
  title: string;
  /**
   * Release Group
   */
  release_group: string;
  /**
   * Resolution
   */
  resolution: string;
};

/**
 * SeenReleaseAddResult
 */
export type SeenReleaseAddResult = {
  /**
   * Additional
   */
  additional: number;
  /**
   * Episodes
   */
  episodes: Array<number>;
};

/**
 * Show
 */
export type Show = {
  /**
   * Id
   */
  id_: number;
  /**
   * Library Id
   */
  library_id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Title Local
   */
  title_local: string | null;
  /**
   * Desired Format
   */
  desired_format: string | null;
  /**
   * Season
   */
  season: number;
  /**
   * Episode Offset
   */
  episode_offset: number;
  /**
   * Watch
   */
  watch: boolean;
  /**
   * Preferred Resolution
   */
  preferred_resolution: string | null;
  /**
   * Preferred Release Group
   */
  preferred_release_group: string | null;
  /**
   * Created At
   */
  created_at: string;
  metadata?: KitsuManager | null;
  /**
   * Entries
   */
  entries?: Array<Entry>;
  /**
   * Webhooks
   */
  webhooks?: Array<Webhook>;
};

/**
 * ShowCreate
 */
export type ShowCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Title Local
   */
  title_local?: string | null;
  /**
   * Library Id
   */
  library_id: number;
  /**
   * Desired Format
   */
  desired_format?: string | null;
  /**
   * Season
   */
  season: number;
  /**
   * Episode Offset
   */
  episode_offset?: number;
  /**
   * Watch
   */
  watch?: boolean;
  /**
   * Preferred Resolution
   */
  preferred_resolution?: string | null;
  /**
   * Preferred Release Group
   */
  preferred_release_group?: string | null;
};

/**
 * ShowEntryRecord
 *
 * The trimmed entry view returned by the per-show entry listing.
 */
export type ShowEntryRecord = {
  /**
   * Id
   */
  id: number;
  /**
   * Episode
   */
  episode: number;
  /**
   * Current State
   */
  current_state: string;
  /**
   * Torrent Hash
   */
  torrent_hash: string;
};

/**
 * ShowUpdate
 */
export type ShowUpdate = {
  /**
   * Title
   */
  title: string;
  /**
   * Title Local
   */
  title_local?: string | null;
  /**
   * Library Id
   */
  library_id: number;
  /**
   * Desired Format
   */
  desired_format?: string | null;
  /**
   * Season
   */
  season?: number | null;
  /**
   * Episode Offset
   */
  episode_offset?: number | null;
  /**
   * Watch
   */
  watch?: boolean | null;
  /**
   * Kitsu Id
   */
  kitsu_id?: number | null;
  /**
   * Preferred Resolution
   */
  preferred_resolution?: string | null;
  /**
   * Preferred Release Group
   */
  preferred_release_group?: string | null;
};

/**
 * ShowsPage
 */
export type ShowsPage = {
  /**
   * Shows
   */
  shows: Array<Show>;
  pagination: Pagination;
};

/**
 * Success[DirectoryTree]
 */
export type SuccessDirectoryTree = {
  /**
   * Status
   */
  status?: number;
  result: DirectoryTree;
};

/**
 * Success[Entry]
 */
export type SuccessEntry = {
  /**
   * Status
   */
  status?: number;
  result: Entry;
};

/**
 * Success[FeedsConfigResponse]
 */
export type SuccessFeedsConfigResponse = {
  /**
   * Status
   */
  status?: number;
  result: FeedsConfigResponse;
};

/**
 * Success[GeneralConfigResponse]
 */
export type SuccessGeneralConfigResponse = {
  /**
   * Status
   */
  status?: number;
  result: GeneralConfigResponse;
};

/**
 * Success[Library]
 */
export type SuccessLibrary = {
  /**
   * Status
   */
  status?: number;
  result: Library;
};

/**
 * Success[SeenReleaseAddResult]
 */
export type SuccessSeenReleaseAddResult = {
  /**
   * Status
   */
  status?: number;
  result: SeenReleaseAddResult;
};

/**
 * Success[ShowEntryRecord]
 */
export type SuccessShowEntryRecord = {
  /**
   * Status
   */
  status?: number;
  result: ShowEntryRecord;
};

/**
 * Success[Show]
 */
export type SuccessShow = {
  /**
   * Status
   */
  status?: number;
  result: Show;
};

/**
 * Success[ShowsPage]
 */
export type SuccessShowsPage = {
  /**
   * Status
   */
  status?: number;
  result: ShowsPage;
};

/**
 * Success[TorrentConfigResponse]
 */
export type SuccessTorrentConfigResponse = {
  /**
   * Status
   */
  status?: number;
  result: TorrentConfigResponse;
};

/**
 * Success[TorrentTestResult]
 */
export type SuccessTorrentTestResult = {
  /**
   * Status
   */
  status?: number;
  result: TorrentTestResult;
};

/**
 * Success[WebhookBase]
 */
export type SuccessWebhookBase = {
  /**
   * Status
   */
  status?: number;
  result: WebhookBase;
};

/**
 * Success[Webhook]
 */
export type SuccessWebhook = {
  /**
   * Status
   */
  status?: number;
  result: Webhook;
};

/**
 * Success[bool]
 */
export type SuccessBool = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: boolean;
};

/**
 * Success[list[Entry]]
 */
export type SuccessListEntry = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<Entry>;
};

/**
 * Success[list[FoundEntry]]
 */
export type SuccessListFoundEntry = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<FoundEntry>;
};

/**
 * Success[list[Library]]
 */
export type SuccessListLibrary = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<Library>;
};

/**
 * Success[list[NyaaResult]]
 */
export type SuccessListNyaaResult = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<NyaaResult>;
};

/**
 * Success[list[SeenRelease]]
 */
export type SuccessListSeenRelease = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<SeenRelease>;
};

/**
 * Success[list[ShowEntryRecord]]
 */
export type SuccessListShowEntryRecord = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<ShowEntryRecord>;
};

/**
 * Success[list[WebhookBase]]
 */
export type SuccessListWebhookBase = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<WebhookBase>;
};

/**
 * Success[list[Webhook]]
 */
export type SuccessListWebhook = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<Webhook>;
};

/**
 * Success[list[str]]
 */
export type SuccessListStr = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: Array<string>;
};

/**
 * Success[str]
 */
export type SuccessStr = {
  /**
   * Status
   */
  status?: number;
  /**
   * Result
   */
  result: string;
};

/**
 * TorrentConfigResponse
 */
export type TorrentConfigResponse = {
  /**
   * Client
   */
  client: string;
  /**
   * Host
   */
  host: string;
  /**
   * Port
   */
  port: number;
  /**
   * Username
   */
  username: string | null;
  /**
   * Password
   */
  password: string | null;
  /**
   * Secure
   */
  secure: boolean;
};

/**
 * TorrentConfigUpdate
 */
export type TorrentConfigUpdate = {
  /**
   * Client
   */
  client?: string | null;
  /**
   * Host
   */
  host?: string | null;
  /**
   * Port
   */
  port?: number | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Password
   */
  password?: string | null;
  /**
   * Secure
   */
  secure?: boolean | null;
};

/**
 * TorrentTestResult
 */
export type TorrentTestResult = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Error
   */
  error?: string | null;
};

/**
 * TreeRequest
 */
export type TreeRequest = {
  /**
   * Dir
   */
  dir: string;
  /**
   * Subdir
   */
  subdir?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * Webhook
 */
export type Webhook = {
  /**
   * Show Id
   */
  show_id: number;
  base: WebhookBase;
  /**
   * Triggers
   */
  triggers?: Array<string>;
};

/**
 * WebhookBase
 */
export type WebhookBase = {
  /**
   * Base Id
   */
  base_id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Service
   */
  service: string;
  /**
   * Url
   */
  url: string;
  /**
   * Content Fmt
   */
  content_fmt?: string | null;
  /**
   * Default Triggers
   */
  default_triggers?: Array<string>;
};

/**
 * WebhookBaseCreate
 */
export type WebhookBaseCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Service
   */
  service: string;
  /**
   * Url
   */
  url: string;
  /**
   * Content Fmt
   */
  content_fmt?: string | null;
  /**
   * Default Triggers
   */
  default_triggers?: string;
};

/**
 * WebhookBaseUpdate
 */
export type WebhookBaseUpdate = {
  /**
   * Name
   */
  name: string;
  /**
   * Service
   */
  service: string;
  /**
   * Url
   */
  url: string;
  /**
   * Content Fmt
   */
  content_fmt?: string | null;
  /**
   * Default Triggers
   */
  default_triggers?: string;
};

/**
 * WebhookUpdate
 */
export type WebhookUpdate = {
  /**
   * Triggers
   */
  triggers?: string;
};

/**
 * KitsuManager
 */
export type KitsuManagerWritable = {
  /**
   * Show Id
   */
  show_id: number;
  /**
   * Kitsu Id
   */
  kitsu_id?: number | null;
  /**
   * Slug
   */
  slug?: string | null;
  /**
   * Status
   */
  status?: string | null;
  /**
   * Poster
   */
  poster?: string | null;
};

/**
 * Show
 */
export type ShowWritable = {
  /**
   * Id
   */
  id_: number;
  /**
   * Library Id
   */
  library_id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Title Local
   */
  title_local: string | null;
  /**
   * Desired Format
   */
  desired_format: string | null;
  /**
   * Season
   */
  season: number;
  /**
   * Episode Offset
   */
  episode_offset: number;
  /**
   * Watch
   */
  watch: boolean;
  /**
   * Preferred Resolution
   */
  preferred_resolution: string | null;
  /**
   * Preferred Release Group
   */
  preferred_release_group: string | null;
  /**
   * Created At
   */
  created_at: string;
  metadata?: KitsuManagerWritable | null;
  /**
   * Entries
   */
  entries?: Array<Entry>;
  /**
   * Webhooks
   */
  webhooks?: Array<Webhook>;
};

/**
 * ShowsPage
 */
export type ShowsPageWritable = {
  /**
   * Shows
   */
  shows: Array<ShowWritable>;
  pagination: Pagination;
};

/**
 * Success[Show]
 */
export type SuccessShowWritable = {
  /**
   * Status
   */
  status?: number;
  result: ShowWritable;
};

/**
 * Success[ShowsPage]
 */
export type SuccessShowsPageWritable = {
  /**
   * Status
   */
  status?: number;
  result: ShowsPageWritable;
};

export type TreeData = {
  body: TreeRequest;
  path?: never;
  query?: never;
  url: "/api/v1/tree";
};

export type TreeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TreeError = TreeErrors[keyof TreeErrors];

export type TreeResponses = {
  /**
   * Successful Response
   */
  200: SuccessDirectoryTree;
};

export type TreeResponse = TreeResponses[keyof TreeResponses];

export type GetApiTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/token";
};

export type GetApiTokenResponses = {
  /**
   * Successful Response
   */
  200: SuccessStr;
};

export type GetApiTokenResponse =
  GetApiTokenResponses[keyof GetApiTokenResponses];

export type RegenerateApiTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/token";
};

export type RegenerateApiTokenResponses = {
  /**
   * Successful Response
   */
  200: SuccessStr;
};

export type RegenerateApiTokenResponse =
  RegenerateApiTokenResponses[keyof RegenerateApiTokenResponses];

export type GetGeneralConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/general";
};

export type GetGeneralConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessGeneralConfigResponse;
};

export type GetGeneralConfigResponse =
  GetGeneralConfigResponses[keyof GetGeneralConfigResponses];

export type UpdateGeneralConfigData = {
  body: GeneralConfigUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/config/general";
};

export type UpdateGeneralConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateGeneralConfigError =
  UpdateGeneralConfigErrors[keyof UpdateGeneralConfigErrors];

export type UpdateGeneralConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessGeneralConfigResponse;
};

export type UpdateGeneralConfigResponse =
  UpdateGeneralConfigResponses[keyof UpdateGeneralConfigResponses];

export type GetFeedsConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/feeds";
};

export type GetFeedsConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessFeedsConfigResponse;
};

export type GetFeedsConfigResponse =
  GetFeedsConfigResponses[keyof GetFeedsConfigResponses];

export type UpdateFeedsConfigData = {
  body: FeedsConfigUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/config/feeds";
};

export type UpdateFeedsConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFeedsConfigError =
  UpdateFeedsConfigErrors[keyof UpdateFeedsConfigErrors];

export type UpdateFeedsConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessFeedsConfigResponse;
};

export type UpdateFeedsConfigResponse =
  UpdateFeedsConfigResponses[keyof UpdateFeedsConfigResponses];

export type GetTorrentConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/torrent";
};

export type GetTorrentConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessTorrentConfigResponse;
};

export type GetTorrentConfigResponse =
  GetTorrentConfigResponses[keyof GetTorrentConfigResponses];

export type UpdateTorrentConfigData = {
  body: TorrentConfigUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/config/torrent";
};

export type UpdateTorrentConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTorrentConfigError =
  UpdateTorrentConfigErrors[keyof UpdateTorrentConfigErrors];

export type UpdateTorrentConfigResponses = {
  /**
   * Successful Response
   */
  200: SuccessTorrentConfigResponse;
};

export type UpdateTorrentConfigResponse =
  UpdateTorrentConfigResponses[keyof UpdateTorrentConfigResponses];

export type TestTorrentClientData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/torrent/test";
};

export type TestTorrentClientResponses = {
  /**
   * Successful Response
   */
  200: SuccessTorrentTestResult;
};

export type TestTorrentClientResponse =
  TestTorrentClientResponses[keyof TestTorrentClientResponses];

export type CheckForReleasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/shows/check";
};

export type CheckForReleasesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListFoundEntry;
};

export type CheckForReleasesResponse =
  CheckForReleasesResponses[keyof CheckForReleasesResponses];

export type DeleteShowCacheData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/cache";
};

export type DeleteShowCacheErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteShowCacheError =
  DeleteShowCacheErrors[keyof DeleteShowCacheErrors];

export type DeleteShowCacheResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteShowCacheResponse =
  DeleteShowCacheResponses[keyof DeleteShowCacheResponses];

export type WebhookIsValidData = {
  body?: never;
  path: {
    /**
     * Base Id
     */
    base_id: number;
  };
  query?: never;
  url: "/api/v1/webhooks/{base_id}/valid";
};

export type WebhookIsValidErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WebhookIsValidError =
  WebhookIsValidErrors[keyof WebhookIsValidErrors];

export type WebhookIsValidResponses = {
  /**
   * Successful Response
   */
  200: SuccessBool;
};

export type WebhookIsValidResponse =
  WebhookIsValidResponses[keyof WebhookIsValidResponses];

export type ChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: "/api/v1/account/change-password";
};

export type ChangePasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangePasswordError =
  ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
  /**
   * Successful Response
   */
  200: SuccessBool;
};

export type ChangePasswordResponse =
  ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetShowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Filters
     */
    filters?: string | null;
    /**
     * Text Filter
     */
    text_filter?: string | null;
    /**
     * Sort Key
     */
    sort_key?: string;
    /**
     * Sort Direction
     */
    sort_direction?: string;
  };
  url: "/api/v1/shows";
};

export type GetShowsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShowsError = GetShowsErrors[keyof GetShowsErrors];

export type GetShowsResponses = {
  /**
   * Successful Response
   */
  200: SuccessShowsPage;
};

export type GetShowsResponse = GetShowsResponses[keyof GetShowsResponses];

export type CreateShowData = {
  body: ShowCreate;
  path?: never;
  query?: never;
  url: "/api/v1/shows";
};

export type CreateShowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateShowError = CreateShowErrors[keyof CreateShowErrors];

export type CreateShowResponses = {
  /**
   * Successful Response
   */
  201: SuccessShow;
};

export type CreateShowResponse = CreateShowResponses[keyof CreateShowResponses];

export type DeleteShowData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}";
};

export type DeleteShowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteShowError = DeleteShowErrors[keyof DeleteShowErrors];

export type DeleteShowResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteShowResponse = DeleteShowResponses[keyof DeleteShowResponses];

export type GetShowData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}";
};

export type GetShowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShowError = GetShowErrors[keyof GetShowErrors];

export type GetShowResponses = {
  /**
   * Successful Response
   */
  200: SuccessShow;
};

export type GetShowResponse = GetShowResponses[keyof GetShowResponses];

export type UpdateShowData = {
  body: ShowUpdate;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}";
};

export type UpdateShowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateShowError = UpdateShowErrors[keyof UpdateShowErrors];

export type UpdateShowResponses = {
  /**
   * Successful Response
   */
  200: SuccessShow;
};

export type UpdateShowResponse = UpdateShowResponses[keyof UpdateShowResponses];

export type GetShowEntriesData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/entries";
};

export type GetShowEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShowEntriesError =
  GetShowEntriesErrors[keyof GetShowEntriesErrors];

export type GetShowEntriesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListShowEntryRecord;
};

export type GetShowEntriesResponse =
  GetShowEntriesResponses[keyof GetShowEntriesResponses];

export type CreateShowEntriesData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/entries";
};

export type CreateShowEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateShowEntriesError =
  CreateShowEntriesErrors[keyof CreateShowEntriesErrors];

export type CreateShowEntriesResponses = {
  /**
   * Response Create Show Entries
   *
   * Successful Response
   */
  201: SuccessEntry | SuccessListEntry;
};

export type CreateShowEntriesResponse =
  CreateShowEntriesResponses[keyof CreateShowEntriesResponses];

export type DeleteShowEntryData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Entry Id
     */
    entry_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/entries/{entry_id}";
};

export type DeleteShowEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteShowEntryError =
  DeleteShowEntryErrors[keyof DeleteShowEntryErrors];

export type DeleteShowEntryResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteShowEntryResponse =
  DeleteShowEntryResponses[keyof DeleteShowEntryResponses];

export type GetShowEntryData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Entry Id
     */
    entry_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/entries/{entry_id}";
};

export type GetShowEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShowEntryError = GetShowEntryErrors[keyof GetShowEntryErrors];

export type GetShowEntryResponses = {
  /**
   * Successful Response
   */
  200: SuccessShowEntryRecord;
};

export type GetShowEntryResponse =
  GetShowEntryResponses[keyof GetShowEntryResponses];

export type GetEntryData = {
  body?: never;
  path: {
    /**
     * Entry Id
     */
    entry_id: number;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}";
};

export type GetEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEntryError = GetEntryErrors[keyof GetEntryErrors];

export type GetEntryResponses = {
  /**
   * Successful Response
   */
  200: SuccessEntry;
};

export type GetEntryResponse = GetEntryResponses[keyof GetEntryResponses];

export type GetShowWebhooksData = {
  body?: never;
  path: {
    /**
     * Show Id
     */
    show_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/webhooks";
};

export type GetShowWebhooksErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShowWebhooksError =
  GetShowWebhooksErrors[keyof GetShowWebhooksErrors];

export type GetShowWebhooksResponses = {
  /**
   * Successful Response
   */
  200: SuccessListWebhook;
};

export type GetShowWebhooksResponse =
  GetShowWebhooksResponses[keyof GetShowWebhooksResponses];

export type UpdateShowWebhookData = {
  body: WebhookUpdate;
  path: {
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Base Id
     */
    base_id: number;
  };
  query?: never;
  url: "/api/v1/shows/{show_id}/webhooks/{base_id}";
};

export type UpdateShowWebhookErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateShowWebhookError =
  UpdateShowWebhookErrors[keyof UpdateShowWebhookErrors];

export type UpdateShowWebhookResponses = {
  /**
   * Successful Response
   */
  200: SuccessWebhook;
};

export type UpdateShowWebhookResponse =
  UpdateShowWebhookResponses[keyof UpdateShowWebhookResponses];

export type GetWebhookBasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/webhooks";
};

export type GetWebhookBasesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListWebhookBase;
};

export type GetWebhookBasesResponse =
  GetWebhookBasesResponses[keyof GetWebhookBasesResponses];

export type CreateWebhookBaseData = {
  body: WebhookBaseCreate;
  path?: never;
  query?: never;
  url: "/api/v1/webhooks";
};

export type CreateWebhookBaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateWebhookBaseError =
  CreateWebhookBaseErrors[keyof CreateWebhookBaseErrors];

export type CreateWebhookBaseResponses = {
  /**
   * Successful Response
   */
  201: SuccessWebhookBase;
};

export type CreateWebhookBaseResponse =
  CreateWebhookBaseResponses[keyof CreateWebhookBaseResponses];

export type DeleteWebhookBaseData = {
  body?: never;
  path: {
    /**
     * Base Id
     */
    base_id: number;
  };
  query?: never;
  url: "/api/v1/webhooks/{base_id}";
};

export type DeleteWebhookBaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteWebhookBaseError =
  DeleteWebhookBaseErrors[keyof DeleteWebhookBaseErrors];

export type DeleteWebhookBaseResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteWebhookBaseResponse =
  DeleteWebhookBaseResponses[keyof DeleteWebhookBaseResponses];

export type GetWebhookBaseData = {
  body?: never;
  path: {
    /**
     * Base Id
     */
    base_id: number;
  };
  query?: never;
  url: "/api/v1/webhooks/{base_id}";
};

export type GetWebhookBaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWebhookBaseError =
  GetWebhookBaseErrors[keyof GetWebhookBaseErrors];

export type GetWebhookBaseResponses = {
  /**
   * Successful Response
   */
  200: SuccessListWebhookBase;
};

export type GetWebhookBaseResponse =
  GetWebhookBaseResponses[keyof GetWebhookBaseResponses];

export type UpdateWebhookBaseData = {
  body: WebhookBaseUpdate;
  path: {
    /**
     * Base Id
     */
    base_id: number;
  };
  query?: never;
  url: "/api/v1/webhooks/{base_id}";
};

export type UpdateWebhookBaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateWebhookBaseError =
  UpdateWebhookBaseErrors[keyof UpdateWebhookBaseErrors];

export type UpdateWebhookBaseResponses = {
  /**
   * Successful Response
   */
  200: SuccessWebhookBase;
};

export type UpdateWebhookBaseResponse =
  UpdateWebhookBaseResponses[keyof UpdateWebhookBaseResponses];

export type FilterSeenReleasesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Release Group
     */
    release_group?: string | null;
    /**
     * Resolution
     */
    resolution?: string | null;
    /**
     * Episode
     */
    episode?: number | null;
  };
  url: "/api/v1/seen_releases/filter";
};

export type FilterSeenReleasesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type FilterSeenReleasesError =
  FilterSeenReleasesErrors[keyof FilterSeenReleasesErrors];

export type FilterSeenReleasesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListSeenRelease;
};

export type FilterSeenReleasesResponse =
  FilterSeenReleasesResponses[keyof FilterSeenReleasesResponses];

export type DistinctSeenReleasesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Field
     */
    field: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Release Group
     */
    release_group?: string | null;
    /**
     * Resolution
     */
    resolution?: string | null;
  };
  url: "/api/v1/seen_releases/distinct";
};

export type DistinctSeenReleasesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DistinctSeenReleasesError =
  DistinctSeenReleasesErrors[keyof DistinctSeenReleasesErrors];

export type DistinctSeenReleasesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListStr;
};

export type DistinctSeenReleasesResponse =
  DistinctSeenReleasesResponses[keyof DistinctSeenReleasesResponses];

export type AddSeenReleasesData = {
  body: SeenReleaseAddRequest;
  path?: never;
  query?: never;
  url: "/api/v1/seen_releases/add";
};

export type AddSeenReleasesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddSeenReleasesError =
  AddSeenReleasesErrors[keyof AddSeenReleasesErrors];

export type AddSeenReleasesResponses = {
  /**
   * Successful Response
   */
  200: SuccessSeenReleaseAddResult;
};

export type AddSeenReleasesResponse =
  AddSeenReleasesResponses[keyof AddSeenReleasesResponses];

export type SearchNyaaData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Page
     */
    page?: number;
  };
  url: "/api/v1/nyaa";
};

export type SearchNyaaErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchNyaaError = SearchNyaaErrors[keyof SearchNyaaErrors];

export type SearchNyaaResponses = {
  /**
   * Successful Response
   */
  200: SuccessListNyaaResult;
};

export type SearchNyaaResponse = SearchNyaaResponses[keyof SearchNyaaResponses];

export type AddNyaaResultData = {
  body: NyaaShowRequest;
  path?: never;
  query?: never;
  url: "/api/v1/nyaa";
};

export type AddNyaaResultErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddNyaaResultError = AddNyaaResultErrors[keyof AddNyaaResultErrors];

export type AddNyaaResultResponses = {
  /**
   * Successful Response
   */
  200: SuccessListEntry;
};

export type AddNyaaResultResponse =
  AddNyaaResultResponses[keyof AddNyaaResultResponses];

export type GetLibrariesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/libraries";
};

export type GetLibrariesResponses = {
  /**
   * Successful Response
   */
  200: SuccessListLibrary;
};

export type GetLibrariesResponse =
  GetLibrariesResponses[keyof GetLibrariesResponses];

export type CreateLibraryData = {
  body: LibraryCreate;
  path?: never;
  query?: never;
  url: "/api/v1/libraries";
};

export type CreateLibraryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateLibraryError = CreateLibraryErrors[keyof CreateLibraryErrors];

export type CreateLibraryResponses = {
  /**
   * Successful Response
   */
  201: SuccessLibrary;
};

export type CreateLibraryResponse =
  CreateLibraryResponses[keyof CreateLibraryResponses];

export type DeleteLibraryData = {
  body?: never;
  path: {
    /**
     * Library Id
     */
    library_id: number;
  };
  query?: never;
  url: "/api/v1/libraries/{library_id}";
};

export type DeleteLibraryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteLibraryError = DeleteLibraryErrors[keyof DeleteLibraryErrors];

export type DeleteLibraryResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteLibraryResponse =
  DeleteLibraryResponses[keyof DeleteLibraryResponses];

export type GetLibraryData = {
  body?: never;
  path: {
    /**
     * Library Id
     */
    library_id: number;
  };
  query?: never;
  url: "/api/v1/libraries/{library_id}";
};

export type GetLibraryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLibraryError = GetLibraryErrors[keyof GetLibraryErrors];

export type GetLibraryResponses = {
  /**
   * Successful Response
   */
  200: SuccessListLibrary;
};

export type GetLibraryResponse = GetLibraryResponses[keyof GetLibraryResponses];

export type UpdateLibraryData = {
  body: LibraryUpdate;
  path: {
    /**
     * Library Id
     */
    library_id: number;
  };
  query?: never;
  url: "/api/v1/libraries/{library_id}";
};

export type UpdateLibraryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateLibraryError = UpdateLibraryErrors[keyof UpdateLibraryErrors];

export type UpdateLibraryResponses = {
  /**
   * Successful Response
   */
  200: SuccessLibrary;
};

export type UpdateLibraryResponse =
  UpdateLibraryResponses[keyof UpdateLibraryResponses];
