// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * ChangePasswordRequest
 */
export const zChangePasswordRequest = z.object({
  current_password: z.string().min(1),
  new_password: z.string().min(8),
});

/**
 * DirectoryTree
 */
export const zDirectoryTree = z.object({
  root_is_writable: z.boolean(),
  can_go_back: z.boolean(),
  current_path: z.string(),
  children: z.array(z.string()),
});

/**
 * EntryState
 *
 * Represents the state of an Entry.
 *
 * Matches exactly with the Postgres enum.
 */
export const zEntryState = z.enum([
  "downloading",
  "downloaded",
  "renamed",
  "moved",
  "completed",
  "failed",
]);

/**
 * Entry
 */
export const zEntry = z.object({
  id: z.int(),
  show_id: z.int(),
  episode: z.int(),
  version: z.string(),
  state: zEntryState,
  torrent_hash: z.string(),
  created_manually: z.boolean(),
  last_update: z.iso.datetime(),
  file_path: z.string().optional(),
});

/**
 * FeedsConfigResponse
 */
export const zFeedsConfigResponse = z.object({
  polling_interval: z.int(),
  complete_check_interval: z.int(),
  fuzzy_cutoff: z.int(),
  seed_ratio_limit: z.number(),
});

/**
 * FeedsConfigUpdate
 */
export const zFeedsConfigUpdate = z.object({
  polling_interval: z.int().nullish(),
  complete_check_interval: z.int().nullish(),
  fuzzy_cutoff: z.int().nullish(),
  seed_ratio_limit: z.number().nullish(),
});

export const zFoundEntry = z.tuple([z.int(), z.int()]);

/**
 * GeneralConfigResponse
 */
export const zGeneralConfigResponse = z.object({
  host: z.string(),
  port: z.int(),
  update_do_check: z.boolean(),
  locale: z.string(),
  log_level: z.string(),
  default_desired_format: z.string(),
  unwatch_when_finished: z.boolean(),
  use_season_folder: z.boolean(),
});

/**
 * GeneralConfigUpdate
 */
export const zGeneralConfigUpdate = z.object({
  host: z.string().nullish(),
  port: z.int().nullish(),
  update_do_check: z.boolean().nullish(),
  locale: z.string().nullish(),
  log_level: z.string().nullish(),
  default_desired_format: z.string().nullish(),
  unwatch_when_finished: z.boolean().nullish(),
  use_season_folder: z.boolean().nullish(),
});

/**
 * KitsuManager
 */
export const zKitsuManager = z.object({
  show_id: z.int(),
  kitsu_id: z.int().nullish(),
  slug: z.string().nullish(),
  status: z.string().nullish(),
  poster: z.string().nullish(),
  link: z.string().nullable(),
  html_status: z.string().nullable(),
});

/**
 * Library
 */
export const zLibrary = z.object({
  id_: z.int(),
  folder: z.string(),
  is_default: z.boolean(),
});

/**
 * LibraryCreate
 */
export const zLibraryCreate = z.object({
  folder: z.string(),
});

/**
 * LibraryUpdate
 */
export const zLibraryUpdate = z.object({
  folder: z.string(),
  is_default: z.boolean().optional().default(false),
});

/**
 * NyaaResult
 */
export const zNyaaResult = z.object({
  show_id: z.int().nullable(),
  title: z.string(),
  published: z.string(),
  torrent_link: z.string(),
  post_link: z.string(),
  size: z.string(),
  seeders: z.int(),
  leechers: z.int(),
});

/**
 * NyaaShowRequest
 */
export const zNyaaShowRequest = z.object({
  show_id: z.int(),
  torrent_link: z.string(),
  overwrite: z.boolean().optional().default(false),
});

/**
 * Pagination
 */
export const zPagination = z.object({
  page: z.int(),
  limit: z.int(),
  total: z.int(),
  pages: z.int(),
});

/**
 * SeenRelease
 */
export const zSeenRelease = z.object({
  title: z.string(),
  release_group: z.string(),
  episode: z.int(),
  resolution: z.string(),
  version: z.string(),
  torrent_destination: z.string(),
  seen_at: z.iso.datetime(),
});

/**
 * SeenReleaseAddRequest
 */
export const zSeenReleaseAddRequest = z.object({
  title: z.string(),
  release_group: z.string(),
  resolution: z.string(),
});

/**
 * SeenReleaseAddResult
 */
export const zSeenReleaseAddResult = z.object({
  additional: z.int(),
  episodes: z.array(z.int()),
});

/**
 * ShowCreate
 */
export const zShowCreate = z.object({
  title: z.string(),
  title_local: z.string().nullish(),
  library_id: z.int(),
  desired_format: z.string().nullish(),
  season: z.int(),
  episode_offset: z.int().optional().default(0),
  watch: z.boolean().optional().default(true),
  preferred_resolution: z.string().nullish(),
  preferred_release_group: z.string().nullish(),
});

/**
 * ShowEntryRecord
 *
 * The trimmed entry view returned by the per-show entry listing.
 */
export const zShowEntryRecord = z.object({
  id: z.int(),
  episode: z.int(),
  current_state: z.string(),
  torrent_hash: z.string(),
});

/**
 * ShowUpdate
 */
export const zShowUpdate = z.object({
  title: z.string(),
  title_local: z.string().nullish(),
  library_id: z.int(),
  desired_format: z.string().nullish(),
  season: z.int().nullish(),
  episode_offset: z.int().nullish(),
  watch: z.boolean().nullish(),
  kitsu_id: z.int().nullish(),
  preferred_resolution: z.string().nullish(),
  preferred_release_group: z.string().nullish(),
});

/**
 * Success[DirectoryTree]
 */
export const zSuccessDirectoryTree = z.object({
  status: z.int().optional().default(200),
  result: zDirectoryTree,
});

/**
 * Success[Entry]
 */
export const zSuccessEntry = z.object({
  status: z.int().optional().default(200),
  result: zEntry,
});

/**
 * Success[FeedsConfigResponse]
 */
export const zSuccessFeedsConfigResponse = z.object({
  status: z.int().optional().default(200),
  result: zFeedsConfigResponse,
});

/**
 * Success[GeneralConfigResponse]
 */
export const zSuccessGeneralConfigResponse = z.object({
  status: z.int().optional().default(200),
  result: zGeneralConfigResponse,
});

/**
 * Success[Library]
 */
export const zSuccessLibrary = z.object({
  status: z.int().optional().default(200),
  result: zLibrary,
});

/**
 * Success[SeenReleaseAddResult]
 */
export const zSuccessSeenReleaseAddResult = z.object({
  status: z.int().optional().default(200),
  result: zSeenReleaseAddResult,
});

/**
 * Success[ShowEntryRecord]
 */
export const zSuccessShowEntryRecord = z.object({
  status: z.int().optional().default(200),
  result: zShowEntryRecord,
});

/**
 * Success[bool]
 */
export const zSuccessBool = z.object({
  status: z.int().optional().default(200),
  result: z.boolean(),
});

/**
 * Success[list[Entry]]
 */
export const zSuccessListEntry = z.object({
  status: z.int().optional().default(200),
  result: z.array(zEntry),
});

/**
 * Success[list[FoundEntry]]
 */
export const zSuccessListFoundEntry = z.object({
  status: z.int().optional().default(200),
  result: z.array(zFoundEntry),
});

/**
 * Success[list[Library]]
 */
export const zSuccessListLibrary = z.object({
  status: z.int().optional().default(200),
  result: z.array(zLibrary),
});

/**
 * Success[list[NyaaResult]]
 */
export const zSuccessListNyaaResult = z.object({
  status: z.int().optional().default(200),
  result: z.array(zNyaaResult),
});

/**
 * Success[list[SeenRelease]]
 */
export const zSuccessListSeenRelease = z.object({
  status: z.int().optional().default(200),
  result: z.array(zSeenRelease),
});

/**
 * Success[list[ShowEntryRecord]]
 */
export const zSuccessListShowEntryRecord = z.object({
  status: z.int().optional().default(200),
  result: z.array(zShowEntryRecord),
});

/**
 * Success[list[str]]
 */
export const zSuccessListStr = z.object({
  status: z.int().optional().default(200),
  result: z.array(z.string()),
});

/**
 * Success[str]
 */
export const zSuccessStr = z.object({
  status: z.int().optional().default(200),
  result: z.string(),
});

/**
 * TorrentConfigResponse
 */
export const zTorrentConfigResponse = z.object({
  client: z.string(),
  host: z.string(),
  port: z.int(),
  username: z.string().nullable(),
  password: z.string().nullable(),
  secure: z.boolean(),
});

/**
 * Success[TorrentConfigResponse]
 */
export const zSuccessTorrentConfigResponse = z.object({
  status: z.int().optional().default(200),
  result: zTorrentConfigResponse,
});

/**
 * TorrentConfigUpdate
 */
export const zTorrentConfigUpdate = z.object({
  client: z.string().nullish(),
  host: z.string().nullish(),
  port: z.int().nullish(),
  username: z.string().nullish(),
  password: z.string().nullish(),
  secure: z.boolean().nullish(),
});

/**
 * TorrentTestResult
 */
export const zTorrentTestResult = z.object({
  success: z.boolean(),
  error: z.string().nullish(),
});

/**
 * Success[TorrentTestResult]
 */
export const zSuccessTorrentTestResult = z.object({
  status: z.int().optional().default(200),
  result: zTorrentTestResult,
});

/**
 * TreeRequest
 */
export const zTreeRequest = z.object({
  dir: z.string(),
  subdir: z.string().nullish(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * WebhookBase
 */
export const zWebhookBase = z.object({
  base_id: z.int(),
  name: z.string(),
  service: z.string(),
  url: z.string(),
  content_fmt: z.string().nullish(),
  default_triggers: z.array(z.string()).optional(),
});

/**
 * Success[WebhookBase]
 */
export const zSuccessWebhookBase = z.object({
  status: z.int().optional().default(200),
  result: zWebhookBase,
});

/**
 * Success[list[WebhookBase]]
 */
export const zSuccessListWebhookBase = z.object({
  status: z.int().optional().default(200),
  result: z.array(zWebhookBase),
});

/**
 * Webhook
 */
export const zWebhook = z.object({
  show_id: z.int(),
  base: zWebhookBase,
  triggers: z.array(z.string()).optional(),
});

/**
 * Show
 */
export const zShow = z.object({
  id_: z.int(),
  library_id: z.int(),
  title: z.string(),
  title_local: z.string().nullable(),
  desired_format: z.string().nullable(),
  season: z.int(),
  episode_offset: z.int(),
  watch: z.boolean(),
  preferred_resolution: z.string().nullable(),
  preferred_release_group: z.string().nullable(),
  created_at: z.iso.datetime(),
  metadata: zKitsuManager.nullish(),
  entries: z.array(zEntry).optional(),
  webhooks: z.array(zWebhook).optional(),
});

/**
 * ShowsPage
 */
export const zShowsPage = z.object({
  shows: z.array(zShow),
  pagination: zPagination,
});

/**
 * Success[Show]
 */
export const zSuccessShow = z.object({
  status: z.int().optional().default(200),
  result: zShow,
});

/**
 * Success[ShowsPage]
 */
export const zSuccessShowsPage = z.object({
  status: z.int().optional().default(200),
  result: zShowsPage,
});

/**
 * Success[Webhook]
 */
export const zSuccessWebhook = z.object({
  status: z.int().optional().default(200),
  result: zWebhook,
});

/**
 * Success[list[Webhook]]
 */
export const zSuccessListWebhook = z.object({
  status: z.int().optional().default(200),
  result: z.array(zWebhook),
});

/**
 * WebhookBaseCreate
 */
export const zWebhookBaseCreate = z.object({
  name: z.string(),
  service: z.string(),
  url: z.string(),
  content_fmt: z.string().nullish(),
  default_triggers: z.string().optional().default(""),
});

/**
 * WebhookBaseUpdate
 */
export const zWebhookBaseUpdate = z.object({
  name: z.string(),
  service: z.string(),
  url: z.string(),
  content_fmt: z.string().nullish(),
  default_triggers: z.string().optional().default(""),
});

/**
 * WebhookUpdate
 */
export const zWebhookUpdate = z.object({
  triggers: z.string().optional().default(""),
});

/**
 * KitsuManager
 */
export const zKitsuManagerWritable = z.object({
  show_id: z.int(),
  kitsu_id: z.int().nullish(),
  slug: z.string().nullish(),
  status: z.string().nullish(),
  poster: z.string().nullish(),
});

/**
 * Show
 */
export const zShowWritable = z.object({
  id_: z.int(),
  library_id: z.int(),
  title: z.string(),
  title_local: z.string().nullable(),
  desired_format: z.string().nullable(),
  season: z.int(),
  episode_offset: z.int(),
  watch: z.boolean(),
  preferred_resolution: z.string().nullable(),
  preferred_release_group: z.string().nullable(),
  created_at: z.iso.datetime(),
  metadata: zKitsuManagerWritable.nullish(),
  entries: z.array(zEntry).optional(),
  webhooks: z.array(zWebhook).optional(),
});

/**
 * ShowsPage
 */
export const zShowsPageWritable = z.object({
  shows: z.array(zShowWritable),
  pagination: zPagination,
});

/**
 * Success[Show]
 */
export const zSuccessShowWritable = z.object({
  status: z.int().optional().default(200),
  result: zShowWritable,
});

/**
 * Success[ShowsPage]
 */
export const zSuccessShowsPageWritable = z.object({
  status: z.int().optional().default(200),
  result: zShowsPageWritable,
});

export const zTreeBody = zTreeRequest;

/**
 * Successful Response
 */
export const zTreeResponse = zSuccessDirectoryTree;

/**
 * Successful Response
 */
export const zGetApiTokenResponse = zSuccessStr;

/**
 * Successful Response
 */
export const zRegenerateApiTokenResponse = zSuccessStr;

/**
 * Successful Response
 */
export const zGetGeneralConfigResponse = zSuccessGeneralConfigResponse;

export const zUpdateGeneralConfigBody = zGeneralConfigUpdate;

/**
 * Successful Response
 */
export const zUpdateGeneralConfigResponse = zSuccessGeneralConfigResponse;

/**
 * Successful Response
 */
export const zGetFeedsConfigResponse = zSuccessFeedsConfigResponse;

export const zUpdateFeedsConfigBody = zFeedsConfigUpdate;

/**
 * Successful Response
 */
export const zUpdateFeedsConfigResponse = zSuccessFeedsConfigResponse;

/**
 * Successful Response
 */
export const zGetTorrentConfigResponse = zSuccessTorrentConfigResponse;

export const zUpdateTorrentConfigBody = zTorrentConfigUpdate;

/**
 * Successful Response
 */
export const zUpdateTorrentConfigResponse = zSuccessTorrentConfigResponse;

/**
 * Successful Response
 */
export const zTestTorrentClientResponse = zSuccessTorrentTestResult;

/**
 * Successful Response
 */
export const zCheckForReleasesResponse = zSuccessListFoundEntry;

export const zDeleteShowCachePath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteShowCacheResponse = z.void();

export const zWebhookIsValidPath = z.object({
  base_id: z.int(),
});

/**
 * Successful Response
 */
export const zWebhookIsValidResponse = zSuccessBool;

export const zChangePasswordBody = zChangePasswordRequest;

/**
 * Successful Response
 */
export const zChangePasswordResponse = zSuccessBool;

export const zGetShowsQuery = z.object({
  page: z.int().gte(1).optional().default(1),
  limit: z.int().gte(1).lte(100).optional().default(17),
  filters: z.string().nullish(),
  text_filter: z.string().nullish(),
  sort_key: z.string().optional().default("title"),
  sort_direction: z.string().optional().default("+"),
});

/**
 * Successful Response
 */
export const zGetShowsResponse = zSuccessShowsPage;

export const zCreateShowBody = zShowCreate;

/**
 * Successful Response
 */
export const zCreateShowResponse = zSuccessShow;

export const zDeleteShowPath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteShowResponse = z.void();

export const zGetShowPath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetShowResponse = zSuccessShow;

export const zUpdateShowBody = zShowUpdate;

export const zUpdateShowPath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateShowResponse = zSuccessShow;

export const zGetShowEntriesPath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetShowEntriesResponse = zSuccessListShowEntryRecord;

export const zCreateShowEntriesPath = z.object({
  show_id: z.int(),
});

/**
 * Response Create Show Entries
 *
 * Successful Response
 */
export const zCreateShowEntriesResponse = z.union([
  zSuccessEntry,
  zSuccessListEntry,
]);

export const zDeleteShowEntryPath = z.object({
  show_id: z.int(),
  entry_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteShowEntryResponse = z.void();

export const zGetShowEntryPath = z.object({
  show_id: z.int(),
  entry_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetShowEntryResponse = zSuccessShowEntryRecord;

export const zGetEntryPath = z.object({
  entry_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetEntryResponse = zSuccessEntry;

export const zGetShowWebhooksPath = z.object({
  show_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetShowWebhooksResponse = zSuccessListWebhook;

export const zUpdateShowWebhookBody = zWebhookUpdate;

export const zUpdateShowWebhookPath = z.object({
  show_id: z.int(),
  base_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateShowWebhookResponse = zSuccessWebhook;

/**
 * Successful Response
 */
export const zGetWebhookBasesResponse = zSuccessListWebhookBase;

export const zCreateWebhookBaseBody = zWebhookBaseCreate;

/**
 * Successful Response
 */
export const zCreateWebhookBaseResponse = zSuccessWebhookBase;

export const zDeleteWebhookBasePath = z.object({
  base_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteWebhookBaseResponse = z.void();

export const zGetWebhookBasePath = z.object({
  base_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetWebhookBaseResponse = zSuccessListWebhookBase;

export const zUpdateWebhookBaseBody = zWebhookBaseUpdate;

export const zUpdateWebhookBasePath = z.object({
  base_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateWebhookBaseResponse = zSuccessWebhookBase;

export const zFilterSeenReleasesQuery = z.object({
  title: z.string().nullish(),
  release_group: z.string().nullish(),
  resolution: z.string().nullish(),
  episode: z.int().nullish(),
});

/**
 * Successful Response
 */
export const zFilterSeenReleasesResponse = zSuccessListSeenRelease;

export const zDistinctSeenReleasesQuery = z.object({
  field: z.string(),
  title: z.string().nullish(),
  release_group: z.string().nullish(),
  resolution: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zDistinctSeenReleasesResponse = zSuccessListStr;

export const zAddSeenReleasesBody = zSeenReleaseAddRequest;

/**
 * Successful Response
 */
export const zAddSeenReleasesResponse = zSuccessSeenReleaseAddResult;

export const zSearchNyaaQuery = z.object({
  query: z.string().nullish(),
  limit: z.int().gte(1).lte(100).optional().default(15),
  page: z.int().gte(1).optional().default(1),
});

/**
 * Successful Response
 */
export const zSearchNyaaResponse = zSuccessListNyaaResult;

export const zAddNyaaResultBody = zNyaaShowRequest;

/**
 * Successful Response
 */
export const zAddNyaaResultResponse = zSuccessListEntry;

/**
 * Successful Response
 */
export const zGetLibrariesResponse = zSuccessListLibrary;

export const zCreateLibraryBody = zLibraryCreate;

/**
 * Successful Response
 */
export const zCreateLibraryResponse = zSuccessLibrary;

export const zDeleteLibraryPath = z.object({
  library_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteLibraryResponse = z.void();

export const zGetLibraryPath = z.object({
  library_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetLibraryResponse = zSuccessListLibrary;

export const zUpdateLibraryBody = zLibraryUpdate;

export const zUpdateLibraryPath = z.object({
  library_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateLibraryResponse = zSuccessLibrary;
