name: Code Quality
on: [push, pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Run Ruff Formatting
        run: uv run ruff format --check

      - name: Run Ruff Linting
        run: uv run ruff check

      - name: Run ty Type Checking
        run: uv run ty check

      - name: Run Tests
        run: uv run pytest

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install JS dependencies
        run: bun install

      - name: Run Prettier Check
        run: bun run prettier . --check
